version: '3'
services:
  user-service:
    build: ./user_service
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - SERVICE_NAME=user-service

  workout-service:
    build: ./workout_service
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    environment:
      - SERVICE_NAME=workout-service

networks:
  default:
    name: microservices-network